# Generated by Django 4.0 on 2021-12-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
