# Generated by Django 4.0 on 2021-12-12 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_purchasehistory_product_alter_tag_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
